FROM python:3.11-slim

WORKDIR /app

COPY services/collector/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY shared/ ./shared/
COPY services/collector/ .

CMD ["python", "main.py"]
